version: '3'

services:
  web:
    build: .
    command: python project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - "8000:8000"
      - "8080:8080"
    expose:
      - "8000"
      - "8080"
