# Generated by Django 3.0.6 on 2020-05-05 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200505_1612'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='rating',
            index_together={('user', 'video')},
        ),
    ]
